// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: product.proto

package productpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BikeType int32

const (
	BikeType_BIKE_TYPE_UNSPECIFIED BikeType = 0
	BikeType_ROAD                  BikeType = 1
	BikeType_MOUNTAIN              BikeType = 2
	BikeType_HYBRID                BikeType = 3
	BikeType_ELECTRIC              BikeType = 4
)

// Enum value maps for BikeType.
var (
	BikeType_name = map[int32]string{
		0: "BIKE_TYPE_UNSPECIFIED",
		1: "ROAD",
		2: "MOUNTAIN",
		3: "HYBRID",
		4: "ELECTRIC",
	}
	BikeType_value = map[string]int32{
		"BIKE_TYPE_UNSPECIFIED": 0,
		"ROAD":                  1,
		"MOUNTAIN":              2,
		"HYBRID":                3,
		"ELECTRIC":              4,
	}
)

func (x BikeType) Enum() *BikeType {
	p := new(BikeType)
	*p = x
	return p
}

func (x BikeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BikeType) Descriptor() protoreflect.EnumDescriptor {
	return file_product_proto_enumTypes[0].Descriptor()
}

func (BikeType) Type() protoreflect.EnumType {
	return &file_product_proto_enumTypes[0]
}

func (x BikeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BikeType.Descriptor instead.
func (BikeType) EnumDescriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

type Feature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *Feature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Feature) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Type          BikeType               `protobuf:"varint,6,opt,name=type,proto3,enum=product.v1.BikeType" json:"type,omitempty"`
	Brand         string                 `protobuf:"bytes,7,opt,name=brand,proto3" json:"brand,omitempty"`
	Size          string                 `protobuf:"bytes,8,opt,name=size,proto3" json:"size,omitempty"`
	Color         string                 `protobuf:"bytes,9,opt,name=color,proto3" json:"color,omitempty"`
	Weight        float64                `protobuf:"fixed64,10,opt,name=weight,proto3" json:"weight,omitempty"`
	Rating        float64                `protobuf:"fixed64,11,opt,name=rating,proto3" json:"rating,omitempty"`
	IsActive      bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Features      []*Feature             `protobuf:"bytes,15,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductResponse) GetType() BikeType {
	if x != nil {
		return x.Type
	}
	return BikeType_BIKE_TYPE_UNSPECIFIED
}

func (x *ProductResponse) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ProductResponse) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ProductResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ProductResponse) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProductResponse) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ProductResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProductResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ProductResponse) GetFeatures() []*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Type          BikeType               `protobuf:"varint,5,opt,name=type,proto3,enum=product.v1.BikeType" json:"type,omitempty"`
	Brand         string                 `protobuf:"bytes,6,opt,name=brand,proto3" json:"brand,omitempty"`
	Size          string                 `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	Color         string                 `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`
	Weight        float64                `protobuf:"fixed64,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Features      []*Feature             `protobuf:"bytes,10,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateProductRequest) GetType() BikeType {
	if x != nil {
		return x.Type
	}
	return BikeType_BIKE_TYPE_UNSPECIFIED
}

func (x *CreateProductRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateProductRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *CreateProductRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateProductRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateProductRequest) GetFeatures() []*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Price         *float64               `protobuf:"fixed64,4,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Quantity      *int32                 `protobuf:"varint,5,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Type          *BikeType              `protobuf:"varint,6,opt,name=type,proto3,enum=product.v1.BikeType,oneof" json:"type,omitempty"`
	Brand         *string                `protobuf:"bytes,7,opt,name=brand,proto3,oneof" json:"brand,omitempty"`
	Size          *string                `protobuf:"bytes,8,opt,name=size,proto3,oneof" json:"size,omitempty"`
	Color         *string                `protobuf:"bytes,9,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Weight        *float64               `protobuf:"fixed64,10,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	Features      []*Feature             `protobuf:"bytes,11,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetQuantity() int32 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *UpdateProductRequest) GetType() BikeType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return BikeType_BIKE_TYPE_UNSPECIFIED
}

func (x *UpdateProductRequest) GetBrand() string {
	if x != nil && x.Brand != nil {
		return *x.Brand
	}
	return ""
}

func (x *UpdateProductRequest) GetSize() string {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return ""
}

func (x *UpdateProductRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *UpdateProductRequest) GetWeight() float64 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *UpdateProductRequest) GetFeatures() []*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProductFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []BikeType             `protobuf:"varint,1,rep,packed,name=types,proto3,enum=product.v1.BikeType" json:"types,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,2,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,3,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Brands        []string               `protobuf:"bytes,4,rep,name=brands,proto3" json:"brands,omitempty"`
	Sizes         []string               `protobuf:"bytes,5,rep,name=sizes,proto3" json:"sizes,omitempty"`
	SortBy        string                 `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	OnlyActive    bool                   `protobuf:"varint,8,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductFilter) Reset() {
	*x = ProductFilter{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductFilter) ProtoMessage() {}

func (x *ProductFilter) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductFilter.ProtoReflect.Descriptor instead.
func (*ProductFilter) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductFilter) GetTypes() []BikeType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ProductFilter) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ProductFilter) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ProductFilter) GetBrands() []string {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *ProductFilter) GetSizes() []string {
	if x != nil {
		return x.Sizes
	}
	return nil
}

func (x *ProductFilter) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ProductFilter) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *ProductFilter) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Filter        *ProductFilter         `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetFilter() *ProductFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ChangeStockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	QuantityChange int32                  `protobuf:"varint,2,opt,name=quantity_change,json=quantityChange,proto3" json:"quantity_change,omitempty"`
	OrderId        string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChangeStockRequest) Reset() {
	*x = ChangeStockRequest{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStockRequest) ProtoMessage() {}

func (x *ChangeStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStockRequest.ProtoReflect.Descriptor instead.
func (*ChangeStockRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ChangeStockRequest) GetQuantityChange() int32 {
	if x != nil {
		return x.QuantityChange
	}
	return 0
}

func (x *ChangeStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\n" +
	"product.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"3\n" +
	"\aFeature\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xe7\x03\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12(\n" +
	"\x04type\x18\x06 \x01(\x0e2\x14.product.v1.BikeTypeR\x04type\x12\x14\n" +
	"\x05brand\x18\a \x01(\tR\x05brand\x12\x12\n" +
	"\x04size\x18\b \x01(\tR\x04size\x12\x14\n" +
	"\x05color\x18\t \x01(\tR\x05color\x12\x16\n" +
	"\x06weight\x18\n" +
	" \x01(\x01R\x06weight\x12\x16\n" +
	"\x06rating\x18\v \x01(\x01R\x06rating\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12/\n" +
	"\bfeatures\x18\x0f \x03(\v2\x13.product.v1.FeatureR\bfeatures\"\xb1\x02\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12(\n" +
	"\x04type\x18\x05 \x01(\x0e2\x14.product.v1.BikeTypeR\x04type\x12\x14\n" +
	"\x05brand\x18\x06 \x01(\tR\x05brand\x12\x12\n" +
	"\x04size\x18\a \x01(\tR\x04size\x12\x14\n" +
	"\x05color\x18\b \x01(\tR\x05color\x12\x16\n" +
	"\x06weight\x18\t \x01(\x01R\x06weight\x12/\n" +
	"\bfeatures\x18\n" +
	" \x03(\v2\x13.product.v1.FeatureR\bfeatures\"\xcf\x03\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x04 \x01(\x01H\x02R\x05price\x88\x01\x01\x12\x1f\n" +
	"\bquantity\x18\x05 \x01(\x05H\x03R\bquantity\x88\x01\x01\x12-\n" +
	"\x04type\x18\x06 \x01(\x0e2\x14.product.v1.BikeTypeH\x04R\x04type\x88\x01\x01\x12\x19\n" +
	"\x05brand\x18\a \x01(\tH\x05R\x05brand\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\b \x01(\tH\x06R\x04size\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\t \x01(\tH\aR\x05color\x88\x01\x01\x12\x1b\n" +
	"\x06weight\x18\n" +
	" \x01(\x01H\bR\x06weight\x88\x01\x01\x12/\n" +
	"\bfeatures\x18\v \x03(\v2\x13.product.v1.FeatureR\bfeaturesB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_priceB\v\n" +
	"\t_quantityB\a\n" +
	"\x05_typeB\b\n" +
	"\x06_brandB\a\n" +
	"\x05_sizeB\b\n" +
	"\x06_colorB\t\n" +
	"\a_weight\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xfc\x01\n" +
	"\rProductFilter\x12*\n" +
	"\x05types\x18\x01 \x03(\x0e2\x14.product.v1.BikeTypeR\x05types\x12\x1b\n" +
	"\tmin_price\x18\x02 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x03 \x01(\x01R\bmaxPrice\x12\x16\n" +
	"\x06brands\x18\x04 \x03(\tR\x06brands\x12\x14\n" +
	"\x05sizes\x18\x05 \x03(\tR\x05sizes\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\x12\x1f\n" +
	"\vonly_active\x18\b \x01(\bR\n" +
	"onlyActive\"X\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x121\n" +
	"\x06filter\x18\x02 \x01(\v2\x19.product.v1.ProductFilterR\x06filter\"w\n" +
	"\x12ChangeStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12'\n" +
	"\x0fquantity_change\x18\x02 \x01(\x05R\x0equantityChange\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId*W\n" +
	"\bBikeType\x12\x19\n" +
	"\x15BIKE_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04ROAD\x10\x01\x12\f\n" +
	"\bMOUNTAIN\x10\x02\x12\n" +
	"\n" +
	"\x06HYBRID\x10\x03\x12\f\n" +
	"\bELECTRIC\x10\x042\xae\x04\n" +
	"\x0eProductService\x12N\n" +
	"\rCreateProduct\x12 .product.v1.CreateProductRequest\x1a\x1b.product.v1.ProductResponse\x12N\n" +
	"\rUpdateProduct\x12 .product.v1.UpdateProductRequest\x1a\x1b.product.v1.ProductResponse\x12I\n" +
	"\rDeleteProduct\x12 .product.v1.DeleteProductRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x12ChangeProductStock\x12\x1e.product.v1.ChangeStockRequest\x1a\x1b.product.v1.ProductResponse\x12H\n" +
	"\n" +
	"GetProduct\x12\x1d.product.v1.GetProductRequest\x1a\x1b.product.v1.ProductResponse\x12H\n" +
	"\fListProducts\x12\x19.product.v1.ProductFilter\x1a\x1b.product.v1.ProductResponse0\x01\x12J\n" +
	"\x0eSearchProducts\x12\x19.product.v1.SearchRequest\x1a\x1b.product.v1.ProductResponse0\x01B5Z3BikeStoreGolang/api-gateway/proto/product;productpbb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_product_proto_goTypes = []any{
	(BikeType)(0),                 // 0: product.v1.BikeType
	(*Feature)(nil),               // 1: product.v1.Feature
	(*ProductResponse)(nil),       // 2: product.v1.ProductResponse
	(*CreateProductRequest)(nil),  // 3: product.v1.CreateProductRequest
	(*UpdateProductRequest)(nil),  // 4: product.v1.UpdateProductRequest
	(*DeleteProductRequest)(nil),  // 5: product.v1.DeleteProductRequest
	(*GetProductRequest)(nil),     // 6: product.v1.GetProductRequest
	(*ProductFilter)(nil),         // 7: product.v1.ProductFilter
	(*SearchRequest)(nil),         // 8: product.v1.SearchRequest
	(*ChangeStockRequest)(nil),    // 9: product.v1.ChangeStockRequest
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_product_proto_depIdxs = []int32{
	0,  // 0: product.v1.ProductResponse.type:type_name -> product.v1.BikeType
	10, // 1: product.v1.ProductResponse.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: product.v1.ProductResponse.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: product.v1.ProductResponse.features:type_name -> product.v1.Feature
	0,  // 4: product.v1.CreateProductRequest.type:type_name -> product.v1.BikeType
	1,  // 5: product.v1.CreateProductRequest.features:type_name -> product.v1.Feature
	0,  // 6: product.v1.UpdateProductRequest.type:type_name -> product.v1.BikeType
	1,  // 7: product.v1.UpdateProductRequest.features:type_name -> product.v1.Feature
	0,  // 8: product.v1.ProductFilter.types:type_name -> product.v1.BikeType
	7,  // 9: product.v1.SearchRequest.filter:type_name -> product.v1.ProductFilter
	3,  // 10: product.v1.ProductService.CreateProduct:input_type -> product.v1.CreateProductRequest
	4,  // 11: product.v1.ProductService.UpdateProduct:input_type -> product.v1.UpdateProductRequest
	5,  // 12: product.v1.ProductService.DeleteProduct:input_type -> product.v1.DeleteProductRequest
	9,  // 13: product.v1.ProductService.ChangeProductStock:input_type -> product.v1.ChangeStockRequest
	6,  // 14: product.v1.ProductService.GetProduct:input_type -> product.v1.GetProductRequest
	7,  // 15: product.v1.ProductService.ListProducts:input_type -> product.v1.ProductFilter
	8,  // 16: product.v1.ProductService.SearchProducts:input_type -> product.v1.SearchRequest
	2,  // 17: product.v1.ProductService.CreateProduct:output_type -> product.v1.ProductResponse
	2,  // 18: product.v1.ProductService.UpdateProduct:output_type -> product.v1.ProductResponse
	11, // 19: product.v1.ProductService.DeleteProduct:output_type -> google.protobuf.Empty
	2,  // 20: product.v1.ProductService.ChangeProductStock:output_type -> product.v1.ProductResponse
	2,  // 21: product.v1.ProductService.GetProduct:output_type -> product.v1.ProductResponse
	2,  // 22: product.v1.ProductService.ListProducts:output_type -> product.v1.ProductResponse
	2,  // 23: product.v1.ProductService.SearchProducts:output_type -> product.v1.ProductResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	file_product_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		EnumInfos:         file_product_proto_enumTypes,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
