name: CI/CD Pipeline for API Gateway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./api-gateway
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }}
        build-args: |
          BUILDKIT_INLINE_CACHE=1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Configure Minikube
      run: |
        minikube start --driver=docker
        minikube addons enable ingress

    - name: Terraform Apply
      working-directory: ./infra/terraform
      run: |
        terraform init
        terraform apply -auto-approve -var="docker_image=${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }}"