name: CI/CD Pipeline for API Gateway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Configure Minikube
      run: |
        minikube start --driver=docker
        minikube addons enable ingress

    - name: Terraform Apply
      working-directory: ./infra/terraform
      run: |
        terraform init
        terraform apply -auto-approve -var="docker_image=${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }}"